package pe.edu.upc.smartdrive.platform.iam.interfaces.rest.resources;

/**
 * Request body an admin submits to register a seller. The username is derived from the
 * company domain and {@code code}; the password is generated by the system.
 */
public record RegisterSellerResource(String firstName, String lastName, String code,
                                     String dni, String phone) {
}
